### ISSUE TITLE
Run model at European scale

### ISSUE THREAD

**Issue by jensdebruijn** [GEB-model/GEB#27]
This is an overarching issue to tack progress to run GEB in all of Europe:

- [ ] [Implement simple crop rotations globally](https://github.com/GEB-model/hydromt_geb/issues/33)
- [ ] [Run multiple basins at once](https://github.com/GEB-model/GEB/issues/7)
- [ ] [Efficiently handle ERA5 data across large scales](https://github.com/GEB-model/hydromt_geb/issues/34)
- [ ] [Run model for all of Europe](https://github.com/GEB-model/GEB/issues/26)
- [ ] [Run calibration procedure for all of Europe](https://github.com/GEB-model/GEB/issues/25)

**Comment by TimBusker** [comment]
Milestone reached: Europe run completed!
